stages:
  - test
  - build
  - deploy

image: ubuntu:latest

build-backend:
  tags:
    - prod
  stage: build
  rules:
    - changes:
      - backend/**/*
  when: manual
  image: docker:20.10
  script:
    - cd backend/
    - docker build -t app-backend:latest .
    - docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN $REGISTRY_NAME
    - docker tag app-backend:latest $REGISTRY_NAME/adelin.bacanu/idp/app-backend:latest
    - docker image ls
    - docker image push $REGISTRY_NAME/adelin.bacanu/idp/app-backend:latest

test-job1:
  stage: test
  when: manual
  script:
    - echo "This job tests something"

deploy-prod:
  stage: deploy
  when: manual
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

