version: "3.8"
services:
  frontend:
    image: frontend
    build: ./frontend/frontend-idpweb
    ports:
      - 9095:9095

  backend:
    image: backend
    build: ./backend
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_PORT: 3306
    entrypoint: ["java","-jar","./app.jar", ]
    ports:
      - 8082:8082

  mysql:
    image: mysql:8-oracle
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: