version: "3.8"
services:
  backend:
    build: ./backend
    networks:
      - backend

  mysql:
    image: mysql:8-oracle
    restart: always
    ports:
      - 3306:3306
    environment: 
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - mysql-data:/var/lib/mysql
    networks: 
      - backend

volumes:
  mysql-data:

networks:
  backend:
