services:
  mysql:
    image: mysql:8-oracle
    restart: always
    ports:
      - 3306:3306
    environment: 
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: