spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
#  liquibase:
#    enabled: true
#    change-log: db/changelog/db.changelog-master.xml
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: epay.rachetutele@gmail.com
    password: Itscoronatime19
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
server:
  port: 8082
